### ISSUE TITLE
Support strict mode with react v18

### ISSUE THREAD

**Issue by 100terres** [react-forked/dnd#317]
Related issue from original repo: https://github.com/atlassian/react-beautiful-dnd/issues/2350

**Comment by antoinejaussoin** [comment]
+1 ⭐️

**Comment by nunocaseiro** [comment]
+1 ⭐️

**Comment by KatFishSnake** [comment]
+1 ⭐️

**Comment by Danzo7** [comment]
+1

**Comment by shivamtomar3** [comment]
+1

**Comment by ximex** [comment]
pls don't only add +1 comments. instead add a thumb-up reaction on the first comment

**Comment by 100terres** [comment]
Hi @antoinejaussoin, @nunocaseiro, @KatFishSnake, @Danzo7, @ximex and @AntonOfTheWoods :wave: 

Thank you for your support. 

Sorry for the radio silence :disappointed:

I had some minor health issues and I needed to take a step back from open source development. In the upcoming days/weeks, I'll try to dedicate time in my schedule to make sure [@react-forked/dnd](https://github.com/react-forked/dnd) support React 18.

**Comment by KatFishSnake** [comment]
@100terres if you can break the work down to tasks, I can help you do it, we just did the migration on our codebase so i have some xp

**Comment by 100terres** [comment]
I everyone I'll publish later today a better version supporting react 18 and strict mode.
